name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.processor.txt
        pip install -r tests/requirements.txt
    
    - name: Run linting
      run: |
        pip install ruff
        ruff check .
    
    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-report=html
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: backend
        name: backend-coverage

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web-ui/package-lock.json
    
    - name: Install dependencies
      working-directory: ./web-ui
      run: npm ci
    
    - name: Run linting
      working-directory: ./web-ui
      run: npm run lint
    
    - name: Run unit tests
      working-directory: ./web-ui
      run: npm run test -- --run --coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./web-ui/coverage
        flags: frontend
        name: frontend-coverage

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web-ui/package-lock.json
    
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.processor.txt
    
    - name: Install frontend dependencies
      working-directory: ./web-ui
      run: npm ci
    
    - name: Install Playwright browsers
      working-directory: ./web-ui
      run: npx playwright install --with-deps
    
    - name: Setup test database and users
      run: |
        python scripts/setup_test_users.py
      env:
        DATABASE_URL: sqlite:///test.db
    
    - name: Start backend server
      run: |
        python ai_processor/main.py &
        sleep 5
      env:
        FLASK_ENV: testing
        DATABASE_URL: sqlite:///test.db
        SECRET_KEY: test-secret-key-for-ci
        CORS_ORIGINS: http://localhost:5173
    
    - name: Start frontend dev server
      working-directory: ./web-ui
      run: |
        npm run dev &
        sleep 10
      env:
        VITE_API_URL: http://localhost:8000
    
    - name: Run E2E tests
      working-directory: ./web-ui
      run: npm run test:e2e
      env:
        CI: true
        E2E_BASE_URL: http://localhost:5173
        E2E_API_URL: http://localhost:8000
        E2E_USERNAME: testuser
        E2E_PASSWORD: testpass
        E2E_ADMIN_USER: admin
        E2E_ADMIN_PASS: admin123
        E2E_VIEWER_USER: viewer
        E2E_VIEWER_PASS: viewer123
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: web-ui/playwright-report/
        retention-days: 30

  integration-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.processor.txt
        pip install -r requirements.capture.txt
        pip install -r tests/requirements.txt
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
      env:
        DATABASE_URL: sqlite:///test.db

  all-tests-pass:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, e2e-tests, integration-tests]
    steps:
      - name: All tests passed
        run: echo "All tests passed successfully!"